### ISSUE TITLE
docker-compose error

### ISSUE THREAD

**Issue by tdiethe** [IRC-SPHERE/Hyperstream-Dockerfiles#6]
Output of `docker compose up`

```
Creating network "hyperstreamdockerfiles_default" with the default driver
Pulling hyperstream-mqtt (toke/mosquitto:latest)...
latest: Pulling from toke/mosquitto
9f0706ba7422: Pull complete
b65569eb2b31: Pull complete
b295efedaccb: Pull complete
114e19adcb87: Pull complete
483398f8d5ee: Pull complete
3138e7accaf3: Pull complete
Digest: sha256:3b893d1478a76b2d88e1ca05ec49ec894fe4912810b995579e042e18a705e5d1
Status: Downloaded newer image for toke/mosquitto:latest
Creating hyperstreamdockerfiles_hyperstream-mqtt_1 ...
Creating hyperstreamdockerfiles_hyperstream-mongo_1 ...
Creating hyperstreamdockerfiles_hyperstream-mqtt_1
Creating hyperstreamdockerfiles_hyperstream-mongo_1 ... done
Creating hyperstreamdockerfiles_hyperstream_1 ...
Creating hyperstreamdockerfiles_hyperstream_1 ... done

ERROR: for hyperstream-viewer  expected string or buffer
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 68, in main
    command()
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 118, in perform_command
    handler(command, command_options)
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 926, in up
    scale_override=parse_scale_args(options['--scale']),
  File "/usr/local/lib/python2.7/dist-packages/compose/project.py", line 424, in up
    get_deps
  File "/usr/local/lib/python2.7/dist-packages/compose/parallel.py", line 69, in parallel_execute
    raise error_to_reraise
TypeError: expected string or buffer
```

**Comment by So-Cool** [comment]
Seems like the Docker issue: docker/compose#4972  
Docker has been updated couple hours ago and the new version is broken

**Comment by tdiethe** [comment]
Ok workaround is to use `sudo pip install -U docker==2.4.2` for now
